apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels: 
    app: replica-app
spec:
  selector: 
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      name: nginxp
      labels: 
        app: my-app
    spec:
      containers: 
      - name: nginx
        image: nginx